import type { GeneratedContent, FAQItem } from "@/types";

function escapeHtml(text: string | null | undefined): string {
  const value = text ?? "";
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function renderFaqHtml(faq: FAQItem[]): string {
  return faq
    .map(
      (item) => `
    <div class="faq-item">
      <h3 class="faq-question">${escapeHtml(item.question)}</h3>
      <p class="faq-answer">${escapeHtml(item.answer)}</p>
    </div>`
    )
    .join("\n");
}

function renderFeaturesHtml(features: string[]): string {
  return features
    .map((f) => `<li class="feature-item">${escapeHtml(f)}</li>`)
    .join("\n");
}

export function generateHtml(
  content: GeneratedContent,
  imageUrls: string[] = []
): string {
  const imagesHtml = imageUrls
    .map(
      (url) =>
        `<img src="${escapeHtml(url)}" alt="${escapeHtml(content.title)}" class="product-image" />`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="${escapeHtml(content.seoKeywords.join(", "))}">
  <title>${escapeHtml(content.title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif; color: #1a1a1a; line-height: 1.6; background: #fff; }
    .container { max-width: 800px; margin: 0 auto; padding: 40px 20px; }
    .thumbnail-badge { display: inline-block; background: #ff4757; color: #fff; padding: 8px 16px; border-radius: 4px; font-weight: 700; font-size: 14px; margin-bottom: 20px; }
    h1 { font-size: 28px; font-weight: 700; margin-bottom: 24px; color: #111; }
    .images { display: flex; gap: 12px; flex-wrap: wrap; margin-bottom: 32px; }
    .product-image { width: 100%; max-width: 380px; border-radius: 8px; object-fit: cover; }
    .description { font-size: 16px; color: #333; margin-bottom: 32px; padding: 20px; background: #f8f9fa; border-radius: 8px; }
    .section-title { font-size: 20px; font-weight: 700; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #111; }
    .features { list-style: none; margin-bottom: 32px; }
    .feature-item { padding: 12px 16px; margin-bottom: 8px; background: #f0f4ff; border-left: 4px solid #4a6cf7; border-radius: 0 4px 4px 0; }
    .faq-item { margin-bottom: 20px; padding: 16px; border: 1px solid #e9ecef; border-radius: 8px; }
    .faq-question { font-size: 16px; font-weight: 600; margin-bottom: 8px; color: #111; }
    .faq-answer { font-size: 14px; color: #555; }
    .marketing-copy { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; padding: 24px; border-radius: 12px; margin-bottom: 32px; font-size: 18px; font-weight: 500; text-align: center; }
    .seo-keywords { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 32px; }
    .keyword-tag { background: #e9ecef; color: #495057; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e9ecef; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <span class="thumbnail-badge">${escapeHtml(content.thumbnailText)}</span>
    <h1>${escapeHtml(content.title)}</h1>
    ${imageUrls.length > 0 ? `<div class="images">${imagesHtml}</div>` : ""}
    <div class="description">${escapeHtml(content.description)}</div>
    <div class="marketing-copy">${escapeHtml(content.marketingCopy)}</div>
    <h2 class="section-title">✨ 상품 장점</h2>
    <ul class="features">
      ${renderFeaturesHtml(content.features)}
    </ul>
    <h2 class="section-title">❓ 자주 묻는 질문</h2>
    ${renderFaqHtml(content.faq)}
    <h2 class="section-title">🔍 SEO 키워드</h2>
    <div class="seo-keywords">
      ${content.seoKeywords.map((kw) => `<span class="keyword-tag">#${escapeHtml(kw)}</span>`).join("\n      ")}
    </div>
    <div class="footer">Generated by DetailMaster AI</div>
  </div>
</body>
</html>`;
}

export function generateMarkdown(content: GeneratedContent): string {
  const features = (content.features ?? []).map((f) => `- ${f}`).join("\n");
  const faq = (content.faq ?? [])
    .map((item) => `**Q: ${item.question}**\nA: ${item.answer}`)
    .join("\n\n");
  const keywords = (content.seoKeywords ?? []).map((kw) => `#${kw}`).join(" ");

  return `# ${content.title ?? "상품명"}

> ${content.thumbnailText}

## 상품 설명

${content.description}

## 광고 문구

> ${content.marketingCopy}

## 상품 장점

${features}

## FAQ

${faq}

## SEO 키워드

${keywords}
`;
}

export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
